version: '3'
services:
  postgresdb:
    build:
      context: .
      dockerfile: ./postgresdb/Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - /host_mnt/d/Work/MyProjects/gametest/db/data:/var/lib/postgresql/data
      #- /host_mnt/f/Work/Git/my_project/db/data:/var/lib/postgresql/data  рабочий пример
    env_file:
      - ./postgresdb/env.list
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - DB_HOST=postgresdb
      - DB_PORT=5432
      - ARIA2_RPC_URL=http://aria2:6800/jsonrpc
      - ARIA2_RPC_SECRET=my_secret
      - GAMES_DIRECTORY=/gameLibrary
      - IMAGES_DIRECTORY=/gameLibrary/images
      - JWT_SECRET=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
    volumes:
      - /host_mnt/d/Work/MyProjects/gametest:/gameLibrary
      #- /host_mnt/f/Work/Git/my_project/data:/gameLibrary  рабочий пример
      - /host_mnt/d/Work/MyProjects/gametest/tracker/torrents:/torrentDirTmp
      #- /host_mnt/f/Work/Git/my_project/data/tDir:/torrentDirTmp  рабочий пример
    depends_on:
      postgresdb:
        condition: service_healthy
      aria2:
        condition: service_started
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  aria2:
    image: p3terx/aria2-pro:latest
    container_name: aria2
    ports:
      - "6800:6800"
      - "6888:6888"
      - "6888:6888/udp"
    volumes:
      - ./aria2-config:/config
      - /host_mnt/d/Work/MyProjects/gametest/games:/downloads
     # - /host_mnt/f/Work/Git/my_project/data:/downloads рабочий пример
    environment:
      - PUID=197609
      - PGID=197609
      - TZ=Etc/UTC
      - RPC_SECRET=my_secret
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - DHT=true
      - BT_ENABLE_DHT=true
      - BT_ENABLE_LPD=true
      - ENABLE_PEX=true
      - MAX_CONCURRENT_DOWNLOADS=10
      - MAX_CONNECTION_PER_SERVER=16
      - CONTINUE=true
      - BIND_ADDRESS=0.0.0.0
    restart: unless-stopped

  ariang:
    image: p3terx/ariang:latest
    container_name: ariang
    ports:
      - "6880:6880"
    environment:
      - PUID=197609
      - PGID=197609
      - TZ=Etc/UTC
    restart: unless-stopped
