version: '3'
services:
  game-library-application:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      #- "5432:5432"
      - "9000:9000"
      - "49152-49252:49152-49252"
    environment:
      - TORRENT_TRACKER_PORT=9000 #порт торрент трекера
      - SERVER_PORT=8080 # порт на котором будет запущено приложение в образе
      - DB_HOST=postgresdb #хост для подключения к бд (совпадает с службой бд в докер компоус)
      - APP_HOST=192.168.0.109 #хост для подключения к приложению (совпадает с службой бд в докер компоус)
      - DB_PORT=5432 #порт для подключения к бд
      - TORRENT_TTL=180000 # время жизни торрент клиента
    volumes:
      - /host_mnt/d/Work/MyProjects/gametest:/gameLibrary
      - /host_mnt/d/Work/MyProjects/gametest/tracker/torrents:/torrentDir
  postgresdb:
    build:
      context: .
      dockerfile: ./postgresdb/Dockerfile
    #image: dev/game-library-postgresql:latest
    ports:
      - "5432:5432"
    env_file:
      - ./postgresdb/env.list
  #tracker:
  #  image: opentracker/opentracker
  #  ports:
  #    - 6969:6969
  #  volumes:
  #    - /host_mnt/d/Work/MyProjects/gametest/tracker/data:/data