version: '3'
services:
  game-library-application:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080 # порт на котором будет запущено приложение в образе
      - DB_HOST=postgresdb #хост для подключения к бд (совпадает с службой бд в докер компоус)
      - DB_PORT=5432 #порт для подключения к бд
    volumes:
      - /host_mnt/d/Work/MyProjects/gametest:/gameLibrary
  postgresdb:
    build:
      context: .
      dockerfile: ./postgresdb/Dockerfile
    #image: dev/game-library-postgresql:latest
    ports:
      - "5432:5432"
    volumes:
      - /host_mnt/d/Work/MyProjects/gametest/db/data:/var/lib/postgresql/data
    env_file:
      - ./postgresdb/env.list