server:
  max-http-header-size: 10000KB
  tomcat:
    max-http-form-post-size: 50000KB
    max-file-size: 50000KB
    max-request-size: 50000KB
  port: ${SERVER_PORT}


game-library:
  games:
    directory: ${GAMES_DIRECTORY:/gameLibrary}


spring:
  mvc:
    async:
      request-timeout: 7680000
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/game-library?currentSchema=library
    username: library-manager-user
    password: 2wq345tgfiNcbBBwee3
jpa:
  properties:
    hibernate.default_schema: library
hibernate:
  default_schema: library

entitymanager:
  packages:
    to:
      scan: com.jenikmax.game.library.model.entity

