game-library:
  games:
    directory: D:/Work/MyProjects/gametest
    torrent:
      directory: D:/Work/MyProjects/gametest/torrentDir
      transmission:
        rpc-url: http://localhost:9091/transmission/rpc
        rpc-username: your_username
        rpc-password: your_password


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/game-library?currentSchema=library
    username: library-manager-user
    password: 2wq345tgfiNcbBBwee3
jpa:
  properties:
    hibernate.default_schema: library
hibernate:
  default_schema: library

entitymanager:
  packages:
    to:
      scan: com.jenikmax.game.library.model.entity