server:
  max-http-header-size: 50000KB
  tomcat:
    max-http-form-post-size: 100000KB
    max-file-size: 100000KB
    max-request-size: 100000KB
  port: ${SERVER_PORT}
  servlet:
    context-path: /game-library

game-library:
  games:
    directory: ${GAMES_DIRECTORY:/gameLibrary}
    torrent:
      tracker-host: ${TORRENT_TRACKER_HOST}
      tracker-port: ${TORRENT_TRACKER_PORT}
      ttl: ${TORRENT_TTL:180000}
      directory: ${TORRENT_DIR:/torrentDir}
      directory-tmp: ${TORRENT_DIR_TMP:/torrentDirTmp}

spring:
  mvc:
    async:
      request-timeout: 7680000
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/game-library?currentSchema=library
    username: library-manager-user
    password: 2wq345tgfiNcbBBwee3
jpa:
  properties:
    hibernate.default_schema: library
hibernate:
  default_schema: library

entitymanager:
  packages:
    to:
      scan: com.jenikmax.game.library.model.entity

