server:
  max-http-header-size: 10000KB
  tomcat:
    max-http-form-post-size: 50000KB
    max-file-size: 10000KB
    max-request-size: 10000KB

game-library:
  games:
    directory: D:/Work/MyProjects/gametest
    torrent:
      ttl: 180000
      directory: D:/Work/MyProjects/gametest/torrentDir


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/game-library?currentSchema=library
    username: library-manager-user
    password: 2wq345tgfiNcbBBwee3
jpa:
  properties:
    hibernate.default_schema: library
hibernate:
  default_schema: library

entitymanager:
  packages:
    to:
      scan: com.jenikmax.game.library.model.entity

